[package]
name = "sequence"
version = "0.1.0"
authors = ["Geert-Jan Zwiers <geertjanzwiers@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substring = "1.4.5"
structopt = "0.3.21"